Vauxoo/rma

- crm_claim_rma/__openerp__.py
- crm_claim_rma/crm_claim_rma.py
AttributeError: 'list' object has no attribute 'warranty_return_address' in rma
> [IMP] AttributeError: list object has no attribute warranty_return_address

- crm_claim_rma_number/view/crm_claim_rma.xml
number field is added to tree view in claim line. number is a unique sequence that need display in tree view.
> [ADD] number field is added to tree view in claim line

- crm_rma_advance_location/claim_rma_view.xml
- crm_rma_lot_mass_return/crm_rma_view.xml
Xml id repeated in definition of views
> [FIX] Xml id repeated in definition of views

- crm_claim_rma/crm_claim_rma_view.xml
- crm_rma_lot_mass_return/wizard/returned_lines_from_serial.py
> [ADD] claim_diagnosis field to view

- crm_claim_rma/crm_claim_rma_view.xml
- crm_rma_lot_mass_return/wizard/returned_lines_from_serial.py
- To calcule the warranty to add line with wizard metasearch
- Manually add lines in claim is not allowed
> [ADD] To calcule the warranty to add line with wizard metasearch

- crm_claim_rma/crm_claim_rma.py
- crm_claim_rma/crm_claim_rma_view.xml
- onchange in delivery_address_id is deleted because is not needy
- domain in delivery_adress_id just address of partner_id
- delivery_address is required
- boolean field to pick in the store and depends of this, address is required and invisible
> [IMP] onchange in delivery_address_id is deleted because is not needy

- crm_claim_rma/crm_claim_rma.py
- crm_claim_rma/stock.py
- crm_rma_advance_location/wizard/claim_make_picking_from_picking.py
- crm_rma_claim_make_claim/model/crm_claim_rma.py
- crm_rma_location_rma/stock.py
- crm_rma_lot_mass_return/__openerp__.py
- crm_rma_lot_mass_return/wizard/returned_lines_from_serial.py
- crm_rma_lot_mass_return/wizard/returned_lines_from_serial_wizard_view.xml
- Product is added inline with list
- Description and claim_origine is added in metasearch wizards (just to serial number), is optional, add serial number , claim_origine and description separated by asterik (*)
> 8.0 more info metasearch wizard dev yani

- crm_claim_rma/crm_claim_rma_view.xml
- crm_rma_stock_location/product.py
Grouping by priority and state in claim lines.
> [ADD] grouping by priority and state

- crm_claim_rma/crm_claim_rma.py
- crm_claim_rma/i18n/es.po
- crm_rma_advance_warranty/i18n/es.po
- crm_rma_advance_warranty/model/crm_claim_rma.py
- crm_rma_lot_mass_return/i18n/es.po
- crm_rma_lot_mass_return/wizard/returned_lines_from_serial.py
Translations of warranty field. Valid, Expired and Not define and messages
> 8.0 translations messages rev 2 dev yani

- .travis.yml
Rebasing between OCA and VAUXOO about rma. Version 2.
> 8.0 rebasing oca version 2

- crm_rma_prodlot_invoice/models/sale_order.py
FIX https://github.com/Vauxoo/rma/issues/45
> [FIX] recover all moves for all picking_ids that are comming en the SO

- crm_rma_lot_mass_return/static/lib/alert.js
alert.js was deleted by mistake. Fix #63
> [ADD] alert.js was deleted by mistake. Fix #63

- crm_claim_product_supplier/README.rst
- crm_rma_advance_location/tests/test_make_picking_from_picking.py
- crm_rma_location_rma/README.rst
- crm_rma_location_rma/models/stock_warehouse.py
- crm_rma_location_rma/tests/__init__.py
- crm_rma_location_rma/tests/test_location_rma.py
- crm_rma_lot_mass_return/wizards/returned_lines_from_serial.py
- crm_rma_stock_location/README.rst
- crm_rma_stock_location/models/product_product.py
> Improvements on modules of crm_rma_advance_location, crm_rma_lot_mass_return and crm_rma_stock_location

- crm_rma_lot_mass_return/i18n/crm_rma_lot_mass_return.pot
- crm_rma_lot_mass_return/wizards/returned_lines_from_serial.py
message in wizard is fixed because spelling mistake and translation.
> [FIX] message in wizard is fixed because spelling mistake

- crm_rma_lot_mass_return/i18n/crm_rma_lot_mass_return.pot
- crm_rma_lot_mass_return/i18n/es.po
- crm_rma_lot_mass_return/wizards/returned_lines_from_serial.py
> 8.0 fix message wizard dev yani

- crm_rma_lot_mass_return/tests/test_crm_rma_lot_mass_return_2.py
- crm_rma_lot_mass_return/wizards/returned_lines_from_serial.py
It fixes Vauxoo#73 adding also unit test to challenge values set.
> 8.0 fix crm_rma_lot_mass_return #73

- crm_claim_rma/models/claim_line.py
- crm_claim_rma/tests/test_picking_creation.py
> [FIX] crm_claim_rma: fix Vauxoo/rma#81 missing record name

- crm_rma_lot_mass_return/tests/test_crm_rma_lot_mass_return.py
Random error
``` bash
2015-11-18 21:48:35,093 26433 ERROR rma openerp.addons.crm_rma_lot_mass_return.tests.test_crm_rma_lot_mass_return: ERROR
2015-11-18 21:48:35,093 26433 INFO rma openerp.addons.crm_rma_lot_mass_return.tests.test_crm_rma_lot_mass_return: ======================================================================
2015-11-18 21:48:35,093 26433 ERROR rma openerp.addons.crm_rma_lot_mass_return.tests.test_crm_rma_lot_mass_return: ERROR: test_02_load_products (openerp.addons.crm_rma_lot_mass_return.tests.test_crm_rma_lot_mass_return.TestCrmRmaLotMassReturn)
2015-11-18 21:48:35,093 26433 ERROR rma openerp.addons.crm_rma_lot_mass_return.tests.test_crm_rma_lot_mass_return: Traceback (most recent call last):
2015-11-18 21:48:35,093 26433 ERROR rma …
```
> [FIX] Test invoice is paid for assign invoice_line_id to all lots

- crm_rma_lot_mass_return/tests/test_crm_rma_lot_mass_return_2.py
- crm_rma_lot_mass_return/wizards/returned_lines_from_serial.py
- The items in the wizard could have old items and should be cleaned
- Erros flake fixed
> [IMP] The items in the wizard could have old items and should be cleaned

- crm_rma_lot_mass_return/demo/stock_production_lot.xml
- crm_rma_lot_mass_return/tests/test_crm_rma_lot_mass_return_2.py
- crm_rma_lot_mass_return/wizards/returned_lines_from_serial.py
It gets solved #84 adding a new filter condition when looking for lots..
> [WIP][FIX] crm_rma_lot_mass_return: add filter when looking for lots

- crm_claim_rma/models/claim_line.py
- crm_rma_advance_warranty/models/claim_line.py
Date to calculate warranty is date_invoice
> [IMP] change date of warrant

- crm_claim_rma/i18n/es.po
- crm_claim_rma/i18n/fr.po
- crm_claim_rma/i18n/pt_BR.po
- crm_claim_rma/models/claim_line.py
It is implied that the subject is of the claim, therefore, claim word is erased.
> [IMP] It is implied that the subject is of the claim, therefore, claim word is erased.

- crm_claim_product_supplier/models/claim_line.py
The _compute_supplier_and_supplier_invoice method to calculate the supplier invoice and supplier in a claim line was not taking into consideration when the product does has not serial/lot number.
In this PR, An else is added for to considerer the case when the product does has not serial/lot number, therefore, the last supplier invoice where the product is purchased is returned.
The last supplier invoice with the product in the claim line is found and it is used to filled supplier_invoice_id and supplier_id in the claim.line
> [ADD] Add supplier invoice and supplier in the claim line without serial number

- crm_claim_rma/models/res_company.py
- crm_claim_rma/models/res_users.py
- crm_claim_rma/tests/test_picking_creation.py
- crm_claim_rma/tests/test_rma_configuration.py
- crm_rma_claim_make_claim/tests/test_crm_rma_claim_make_claim.py
- crm_rma_lot_mass_return/wizards/returned_lines_from_serial.py
- crm_rma_prodlot_invoice/models/stock_picking.py
- crm_rma_prodlot_supplier/models/stock_picking.py
- crm_rma_stock_location/models/product_product.py
- crm_rma_stock_location/tests/test_make_picking_from_picking.py
Solve https://github.com/Vauxoo/rma/issues/102
https://github.com/Vauxoo/yoytec/pull/897
> [FIX] pylint errors

- crm_claim_rma/demo/claim_line.xml
Description to humans added in demo claim lines. Improved demo data
> [ADD] Description to humans in demo claim lines

- crm_rma_advance_warranty/__openerp__.py
- crm_rma_claim_make_claim/__openerp__.py
- crm_rma_stock_location/__openerp__.py
> [IMP] improvements in depends

- crm_rma_lot_mass_return/static/src/js/barcode_text.js
- crm_rma_lot_mass_return/tests/test_user_input.py
- crm_rma_lot_mass_return/wizards/returned_lines_from_serial.py
> [![](http://img.youtube.com/vi/v2pglNE6fVY/0.jpg)](http://www.youtube.com/watch?v=v2pglNE6fVY)
> [Asking for review][8.0][crm_rma_lot_mass_return] Fix issues in wizard

- crm_claim_rma/tests/test_crm_claim_code_from_code.py
- crm_claim_rma/tests/test_crm_rma_lot_mass_return_2.py
- crm_claim_rma/tests/test_make_picking_from_picking.py
- crm_claim_rma/tests/test_picking_creation.py
- crm_rma_prodlot_invoice/tests/test_crm_rma_prodlot_supplier.py
- Fix various lints like  E302, E501, C0112
- Refactor `xrange built-in referenced` lint warning using another approach
> [WIP][8.0-purchase] Fix lints and others errors
